### ISSUE TITLE
Data and Art Checklist: Release

### ISSUE THREAD

**Issue by mmgfrcs** [mmgfrcs/project-2k18-se#10]
What to do:
- [ ] All Player Characters
- [ ] All Enemy Characters
- [ ] All Player Animation
- [ ] All Enemy Animation
- [ ] Main Menu UI
- [ ] Character Select UI
- [ ] Game Logo, Banner, Cursor
- [ ] Chances and Events
- [ ] Encounter and Shrine
- [ ] UI Animation

**Comment by mmgfrcs** [comment]
Chances and Events finished on #11 
### Specifications
1. Banner resolution: 1400x600
2. Cursor resolution: 128x128
3. Logo resolution: 512x512 or 1024x1024 (Android Specification)
4. Animation must be 15 frames or more

ZA UTANGNYA JANGAN LUPA
