### ISSUE TITLE
Data and Art Checklist

### ISSUE THREAD

**Issue by mmgfrcs** [mmgfrcs/project-2k18-se#9]
To be completed:
Prototype:
- [ ] Player Data
- [ ] Enemy Data
- [ ] Player Prefab (0/1)
- [ ] Enemy Prefab (0/1)
- [ ] Player Animation
- [ ] Enemy Animation
- [ ] Main Menu UI
- [ ] Character Select UI
- [ ] Game Logo, Banner, Cursor
